/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.junit;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assert classUnderTest.getGreeting().equals("This is not real");
    }
}
